### ISSUE TITLE
Site markers are in slightly incorrect positions

### ISSUE THREAD

**Issue by spiraledgeuk** [spiraledgeuk/bec#9]
Long/lats were worked out by finding buildings on a map, Simtricity has correct values in object browser.

**Comment by scrambledleek** [comment]
I've just checked Simtricity and unfortunately the latitude & longitude values it gives via the 'site' API are for the region associated with the site rather than the site itself (so they are for 'Bristol', or even just 'United Kingdom' in some instances).  The object browser does not provide any extra info.

Corrected values will need to be manually obtained and either:
- hard coded into the web front-end (not recommended, but it's what we have at the moment so would be okay in the short-term), or
- entered into the back-end database and an API provided for the web front-end to retrieve them

**Comment by scrambledleek** [comment]
Updated the hard-coded values in the web front-end.  I think you can close this now.
